notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
branches:
  only:
    - master
install: true
jobs:
  include:
    # maven
    - stage: maven
      name: "Java 8: build"
      jdk: openjdk8
      script:
        - cd $TRAVIS_BUILD_DIR
        - mvn -N io.takari:maven:wrapper -Dmaven=3.6.1
        - ./mvnw
    - stage: maven
      name: "Java 8: versions update"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
    - stage: maven
      name: "Java 11: build"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./mvnw
    - stage: maven
      name: "Java 11: versions update"
      jdk: openjdk11
      script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
cache:
  directories:
    - ~/.m2
